version: '3.9'
services:
  backend:
    build: ./Backend
    ports:
      - "5001:5000"
    volumes:
      - ./Backend/data:/app/data
      - ./Frontend:/app/frontend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FRONTEND_PATH=/app/frontend
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge